services:
  urls-postgres:
    container_name: urls-postgres
    image: postgres
    environment:
      POSTGRES_DB: {POSTGRES_DB}
      POSTGRES_USER: {POSTGRES_USER}
      POSTGRES_PASSWORD: {POSTGRES_PASSWORD}
    volumes:
      - urls-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  urls-data:
